PyLops/pylops

tutorials/marchenko.py
Removed multipoint example from marchenko tutorial to be able to build the documentation in readthedocs
=> Removed multipoint example from marchenko tutorial

environment-dev.yml, requirements-dev.txt, tutorials/deblurring.py, tutorials/interpolation.py
Remove dependency to imageio and go back to scipy to read images. Imageio did not work in readthedocs as it kept finding PIL instead of Pillow
=> Remove dependency to imageio

pylops/LinearOperator.py, pylops/__init__.py, pylops/basicoperators/FunctionOperator.py, pylops/basicoperators/__init__.py, pytests/test_functionoperator.py
Create LinearOperators quickly by calling:
FunctionOperator(f, n)
FunctionOperator(f, nr, nc)
FunctionOperator(f, fc, nc)
or
FunctionOperator(f, fc, nr, nc)
=> Creates FunctionOperator, a useful wrapper for operators defined by generic functions

pylops/__init__.py, pylops/utils/__init__.py, pylops/utils/utils.py, pytests/test_utils.py
This implements the `scooby.Report` properly into `pylops`.
Instead of
```
import scooby
scooby.Report(pylops)
```
you can now simply do
```
pylops.Report()
```
The package `scooby` is not a dependency though. If it is not installed, and `pylops.Report()` is called, it will simply print:
```
NOTE: `pylops.Report` requires `scooby`. Install it via
`pip install scooby` or `conda install -c conda-forge scooby`.
```
=> Properly implement scooby

pylops/__init__.py
If `pylops` is run without properly installing it, then we don't know the version. Till know it resulted in '0.0.0'. We make it here a tiny bit more descriptive, by changing it to 'unknown-'+datestring.
=> Make unknown version more descriptive

docs/source/index.rst
There was an extra space in `* adjoint operator*` that was preventing sphinx from rendering the italics.
=> Small formatting fix in documentation front page

README.md, docs/source/citing.rst, pylops/LinearOperator.py, pylops/basicoperators/Kronecker.py, pytests/test_kronecker.py, pytests/test_linearoperator.py, tutorials/linearoperator.py
The main change in this PR is the fact that now users can sum, subtract, multiply pylops operators and the returned operator maintains all methods and properties as any pylops LinearOperator.
It also contains a bug fix to Kronecker operator ref to #125.
=> [Core] Mathematical operations return LinearOperator

pylops/avo/avo.py, pylops/basicoperators/Spread.py, pylops/optimization/sparsity.py, pylops/signalprocessing/DWT.py, pylops/signalprocessing/FFT.py, pylops/waveeqprocessing/lsm.py, pytests/test_lsm.py, requirements-dev.txt
- Add safeguards when importing optional dependencies to avoid that changes in mandatory dependencies may affect an optional dependencies and lead to an error when loading it within pylops. If the dependency cannot be loaded pylops will still be able to work without it.
- Temporarily remove tests using skfmm for OSX.
=> [Core] Safeguards for optional dependencies

README.md
The first PyLops example in the README is not self-contained, which it probably should be.  Trying to run it results in a `NameError`.
I chose to use a `range` instead of `np.arange`, but I can change that if that would be better.
=> Add two missing variables in README example

pylops/utils/dottest.py
The domain size and range size, `nr` and `nc`, are derived from the operator shape if not provided explicitly.
=> Dottest nr and nc are default None

pylops/avo/poststack.py
Use kind=forward when dealing with L1 regularized inversion
as it makes the inverse problem more stable (no ringing
in solution).
=> Modified FirstDerivative kind in Poststack inversion

README.md, docs/source/api/index.rst, docs/source/credits.rst, examples/plot_conj.py, examples/plot_imag.py, examples/plot_real.py, pylops/LinearOperator.py, pylops/__init__.py, pylops/basicoperators/BlockDiag.py, pylops/basicoperators/Conj.py, pylops/basicoperators/HStack.py, pylops/basicoperators/Imag.py, pylops/basicoperators/Real.py, pylops/basicoperators/VStack.py, pylops/basicoperators/__init__.py, pylops/utils/dottest.py, pytests/test_basicoperators.py, pytests/test_combine.py, pytests/test_linearoperator.py
Many useful linear operators are only linear over real numbers, and
complex numbers when they are treated as being elements of R^2
(e.g., (a+ib) -> (a, b)). These are known as R-linear operators, to
distinguish them from operators that are also linear over complex
numbers (C-linear operators). Examples include operators that
extract the real or imaginary components of the input, and
complex conjugation.
This commit introduces R-linear operators to PyLops. An operator
is specified to be only R-linear (and thus not C-linear) by
setting the new `clinear` attribute on the LinearOperator class
to be False.
When operators are combined, such as by composition or stacking,
the combined operator will be R-linear if any of the component
operators are. This commit implements this in the `dot` method …
=> Adds R-linear operators

pylops/LinearOperator.py
The matrix X created as initial guess to estimate
eigenvalues with lobpcg is now forced to be of same dype
of the operator. Apart from that, two small stylistic changes
are made (two spaces converted into four) and a unused return is
removed.
=> Add dtype to X when using lobpcg for eigs

pylops/LinearOperator.py, pylops/utils/dottest.py, pytests/test_causalintegration.py, pytests/test_combine.py, pytests/test_convolve.py, pytests/test_functionoperator.py, pytests/test_kronecker.py, pytests/test_pad.py, pytests/test_restriction.py, pytests/test_smoothing.py
The dottest is now really using the dytpe of the operator to make u and v. Previously it was mistakenly always using float64 and complex128 so we were most of the time checking the dottest for these types even if the operator was of type single (float32 or complex64). For this reason we also had to modify the tolerance in some of the tests that use single precision.
=> Modified dottest to create u and v with same dtype as operator

pylops/signalprocessing/FFT.py, pylops/signalprocessing/FFT2D.py, pylops/signalprocessing/FFTND.py, pylops/utils/dottest.py, pytests/test_ffts.py
Add scaling to FFTs when using real Fourier transforms
to make them dot-test compliant as proposed in
https://github.com/PyLops/pylops/issues/268.
=> Make all FFTs with real dot-test compliant

pylops/basicoperators/MatrixMult.py, pytests/test_basicoperators.py
The dtype of MatrixMult is checked against that
of the matrix A and upcasted to complex is the
matrix is complex-valued. See https://github.com/PyLops/pylops/issues/257.
=> Automatic casting of dtype in MatrixMult

.gitignore
Excludes local build files in `.eggs/` which are generated when installing with `pip install -e`.
=> Add .eggs/ to .gitignore

.pre-commit-config.yaml
Autopep8 was conflicting with black in a way that successive passes by pre-commit would always change files. Since black is pretty comprehensive, I suggest we just get rid of autopep8 for now.
=> Remove autopep8 hook

.pre-commit-config.yaml
This change avoids conflicts between black and isort.
=> Use the black profile for isort

pytests/test_wavedecomposition.py
In order to speed up our CI pipeline,
https://github.com/PyLops/pylops/issues/285 suggested
to reduce the size of a number of tests, test_wavedecomposition
being one of them. The tests are now running with a smaller
input data.
=> Reduced size of test_wavedecomposition

pylops/signalprocessing/FFT.py, pylops/signalprocessing/FFT2D.py, pylops/signalprocessing/FFTND.py, pytests/test_ffts.py
New features:
* FFT, FFT2D and FFTND now support the SciPy backend. As noted in #286, the SciPy backend respects the precision of the input arrays.
Nitty gritty:
* FFT2D and FFTND now correspond to functions instead of classes, in the same manner as FFT is already implemented. As such, concrete implementations are now relegated to _FFT2D_numpy, _FFT2D_scipy, _FFTND_numpy, _FFTND_scipy
* FFTs for all backends still use the NumPy `fftfreq` and `rfftfreq`. This is OK on the SciPy backend because [SciPy actually uses the NumPy versions under the hood](https://github.com/scipy/scipy/blob/master/scipy/fft/__init__.py#L94).
Test suite:
* Added engine="scipy" to the majority of tests. In addition, setting the scipy backend as the default and then running the entire test suite works without …
=> Implement FFTs using SciPy as backend

pylops/waveeqprocessing/marchenko.py, pylops/waveeqprocessing/mdd.py, pytests/test_marchenko.py, pytests/test_oneway.py
A new optional paramter is added to the Marchenko module
to allow selecting the engine used to perform FFT operations.
=> Added fftengine to Marchenko

pylops/signalprocessing/FFT.py, pytests/test_ffts.py
I noticed a serious bug in the implementation of FFTW. A wrapper class called as such: [`myfftw = pyfftw.FFTW(self.x, self.y, ...)` **always** returns `self.y` on a call](https://github.com/pyFFTW/pyFFTW/blob/master/pyfftw/pyfftw.pyx#L1760-L1762). As such, when using the output of `myfftw()`, we should always be copying this array onto a new one. Not doing this risks overwriting arrays when multiplying by `FFT(engine="fftw")` several times; the same `LinearOperator` is will always write to `self.y`. Note that using some options may force a copy (e.g. `fftshift_after=True`) but this is not guaranteed.
In addition, when calling `myfftw(x)` on an array `x`, [it *may* create a copy of `x`](https://github.com/pyFFTW/pyFFTW/blob/master/pyfftw/pyfftw.pyx#L1751-L1752), which means that …
=> FFTW important bugfix and minor feature

pylops/signalprocessing/FFT.py, pylops/signalprocessing/FFT2D.py, pylops/signalprocessing/FFTND.py, pylops/signalprocessing/_BaseFFTs.py, pytests/test_ffts.py
New features:
* Adds a `norm` parameter to `FFT`, `FFT2D` and `FFTND` (and base respective base classes). Possible values are "ortho" (default), "backward" and "forward" (it might be a good idea to change these names... opinions?).
* Adds `__truediv__` for all FFT operators, obtained by multiplying by the adjoint with the proper scalar
* Improves documentation
* Closes #268 
Implementational details:
* FFTW backend: FFTW supports an equivalent implementation to "ortho" and "backward" through use of keywords. For norm="forward", we just need to scale the forward FFT with 1/N.
* NumPy and SciPy backends: In order to support old versions of these libraries, we only implement "ortho" through the use of the `norm` option in `fft`. "forward" and "backward" are both implemented manually.
=> Feature: Norm option for FFT operator

pylops/utils/signalprocessing.py
This PR vectorizes the loops in `slope_estimate`. The seislet example improves by a factor of ~90x on my machine:
```python
%%timeit -n 100
slope = -pylops.utils.signalprocessing.slope_estimate(d.T, dt, dx, smooth=6)[0]
```
=> feature: Vectorize slope_estimate

examples/plot_seislet.py, pylops/utils/signalprocessing.py
This PR contains several improvements to `slope_estimate`, as well as its usage in `plot_seislet.py`.
Breaking changes:
* `slope_estimate` now returns slopes in the unit `dz/dx`. Motivation: the `slope_estimate` help claims it returns slopes and not angles. Indeed the usage in the seislet transform requires slopes and not angles. However, the current implementation returns `np.arctan((l1 - gzz) / gzx)`, which is an angle, and not a slope. **The new implementation returns `(l1 - gzz) / gzx`**. NB: Luckily the seislet example remains almost the same. Due to fact that x is in meters in the examples, the slopes are in the unit dt/dx, which is very very small, making the small angle approximation (tan θ ≈ θ) valid.
* `smooth` default has been decreased from 20 to 5. Motivation: When `dz` and …
=> Improvements to `slope_estimate`

pylops/signalprocessing/FFT.py, pylops/signalprocessing/FFT2D.py, pylops/signalprocessing/FFTND.py, pylops/signalprocessing/Seislet.py, pylops/signalprocessing/_BaseFFTs.py, pytests/test_ffts.py
This `PR` handles https://github.com/PyLops/pylops/issues/295 for all FFT operators.
Two changes are made:
1. A warning is raised when user selects `nfft<nt`;
2. When the above condition arises, the output of the adjoint is padded after ifft such as it has size `nt`. This way a user can select `nfft<nt` without getting an error when the adjoint is invoked
=> Bug: fix issue with nfft<nt

pylops/optimization/leastsquares.py, pylops/optimization/sparsity.py
Running `pytests/test_sparsity.py` currently produces over 100,000 warnings, mostly due to an issue with how `_halfthreshold` is implemented in `pylops/optimization/sparsity.py`. Currently, it allows division by zero and arccos of values |x| > 1.
In addition, the SciPy cg solver is issuing warnings when it is called without `atol`.
Regarding the first issue, we need to protect division from zero, and clip values above 1 and below -1 so as to be able to apply arrcos.
For the second issue, we add atol='legacy' when atol is not supplied by users.
=> Drastically reduce warnings by patching `spartisty.py` and `leastsquares.py`

docs/source/api/others.rst, examples/plot_causalintegration.py, examples/plot_linearregr.py, examples/plot_regr.py, pylops/LinearOperator.py, pylops/avo/prestack.py, pylops/basicoperators/Block.py, pylops/basicoperators/BlockDiag.py, pylops/basicoperators/LinearRegression.py, pylops/basicoperators/MatrixMult.py, pylops/basicoperators/Regression.py, pylops/basicoperators/Restriction.py, pylops/optimization/leastsquares.py, pylops/optimization/sparsity.py, pylops/signalprocessing/FFT.py, pylops/signalprocessing/FFT2D.py, pylops/signalprocessing/FFTND.py, pylops/utils/describe.py, pylops/utils/signalprocessing.py, pylops/waveeqprocessing/marchenko.py, pylops/waveeqprocessing/oneway.py, pytests/test_oneway.py
This PR contains several improvements to documentation, including math formatting and some language fixes. Most importantly, however, it documents with versionadded/note/warning tags all the changes introduced since the latest stable release v1.16.0.
Following the rationale in #306, I have used version v1.17 as the following major, but this can be amended if #306 is not accepted.
=> Patch docs - v1.17 edition

pylops/basicoperators/Laplacian.py, pytests/test_derivative.py
This PR extends the `Laplacian` operator to perform derivatives over N directions of a N-dimensional array.
Previously the operator could only apply derivatives over up to two directions of a N-dimensional array.
=> Minor: Extend Laplacian to Nd-arrays

pylops/LinearOperator.py, pylops/basicoperators/BlockDiag.py, pylops/basicoperators/HStack.py, pylops/basicoperators/VStack.py, pylops/utils/describe.py, pytests/test_avo.py, pytests/test_basicoperators.py, pytests/test_combine.py, pytests/test_wavedecomposition.py
Some of the private routines in scipy.sparse.linalg.interface have
been moved to scipy.sparse.linalg._interface. Moreover, scipy lsqr
atol and btol have changed in this version to more conservative values,
the old values are forced in PyLops to ensure tests to pass without
loosening up on tolerance.
=> Bugfix: Modifications to handle scipy 1.8.0

pylops/utils/dottest.py
Just refactoring, removing a lot of duplicate code. No functional change.
The only change is that the message always says `^H`, also for real values. I feel that is OK and not wrong, but if preferred I can add that it prints `^T` for real values.
Warning: I have _not_ tested it! I assume the tests that run when I create the PR will do that...
(I am using f-strings, f"{var}", which were introduced in Python 3.6; should be fine I think, or does PyLops still support Python 3.5?)
=> Refactor dottest

.pre-commit-config.yaml, pylops/__init__.py, pylops/avo/__init__.py, pylops/basicoperators/__init__.py, pylops/optimization/__init__.py, pylops/signalprocessing/__init__.py, pylops/waveeqprocessing/__init__.py
This PR revamps the __init__ files with 2 major changes:
- Docstrings are added such that `help(module)` will print some description
- `__all__` lists are used to define what methods in a module will be imported when `from <module> import *`
=> Revamped __init__ files

MIGRATION_V1_V2.md, examples/plot_nmo.py, pylops/utils/dottest.py, pytests/test_derivative.py, pytests/test_ffts.py, pytests/test_functionoperator.py, pytests/test_oneway.py, pytests/test_poststack.py, pytests/test_radon.py, pytests/test_smoothing.py, tutorials/dottest.py
As a follow-up to #335.
We can have the discussion here.
The defaults I set (`rtol=1e-6, atol=1e-21`) corresponds more or less to the status quo I think. Backwards compatibility is given through the kwargs option. So both, keyword and positional arguments will keep working the same way:
```
dottest(Op, nr, nc, tol)
dottest(Op, nr, nc, tol=tol)
```
=> Check passed with np.isclose

pylops/LinearOperator.py, pylops/__init__.py, pylops/avo/__init__.py, pylops/avo/poststack.py, pylops/basicoperators/Diagonal.py, pylops/basicoperators/FirstDerivative.py, pylops/basicoperators/Flip.py, pylops/basicoperators/Gradient.py, pylops/basicoperators/Laplacian.py, pylops/basicoperators/Restriction.py, pylops/basicoperators/Roll.py, pylops/basicoperators/SecondDerivative.py, pylops/basicoperators/Smoothing1D.py, pylops/basicoperators/Smoothing2D.py, pylops/basicoperators/Sum.py, pylops/basicoperators/__init__.py, pylops/optimization/sparsity.py, pylops/signalprocessing/Convolve1D.py, pylops/signalprocessing/Convolve2D.py, pylops/signalprocessing/ConvolveND.py, pylops/signalprocessing/DWT.py, pylops/signalprocessing/DWT2D.py, pylops/signalprocessing/Shift.py, pylops/signalprocessing/_ChirpRadon3D.py, pylops/utils/describe.py, pylops/waveeqprocessing/seismicinterpolation.py
Following #352, but not clo sing it, this PR removes all errors pointed out by the following linting config:
```
[flake8]
ignore = E203, E501, W503, E402
per-file-ignores =
__init__.py: F401, F403, F405
max-line-length = 88
```
A good follow-up to this PR would be to cl ose #352 by incorporating a linter into the development process somehow. Since that is still under debate, this PR will does note attempt that.
=> fix: flake8 warnings and errors

pylops/LinearOperator.py
Following https://github.com/PyLops/pylops/issues/351, this commit includes the possible to choose whether to use scipy (default, for backward compatibility) or numpy solve when dealing with explicit operators.
=> feature: add option to choose dense solver to div

MIGRATION_V1_V2.md, docs/source/api/others.rst, examples/plot_bilinear.py, examples/plot_nmo.py, pylops/LinearOperator.py, pylops/__init__.py, pylops/avo/avo.py, pylops/basicoperators/Symmetrize.py, pylops/config.py, pylops/optimization/leastsquares.py, pylops/optimization/solver.py, pylops/utils/_internal.py, pylops/utils/decorators.py, pytests/test_leastsquares.py, pytests/test_linearoperator.py, pytests/test_solver.py
This PR takes over from #353 in introducing valid multiplication by ND-arrays without the need for reshaping
The current version works like this:
1. Every LOp has `dims` and `dimsd`. They are arbitrary tuples which must be compatible with LOp.shape.
2. Suppose that LOp.dims = (5, 10) and LOp.dimsd = (9, 10). The following shapes are obtained on LOp @ x
|    | Reference   | x.shape                 | (LOp @ x).shape                           | Note                                             |
|----|-------------|-------------------------|-------------------------------------------|--------------------------------------------------|
| V0 | (50,)       | (90,)                   | Standard vector multiplication            |                                                  |
| V1 | (5, 10) …
=> Support for NDArray multiplication

pylops/utils/describe.py
After introducing _SumLinearOperator in LinearOperator instead of using scipy's one (https://github.com/PyLops/pylops/commit/5c1b5cc7c6601a2e70ab647079785928d49f08a6), the describe mehtod should import this class instead of the one from scipy.
=> bugfix: import pylops _SumLinearOperator in describe

MIGRATION_V1_V2.md, examples/plot_ista.py, examples/plot_mdc.py, pylops/signalprocessing/Fredholm1.py, pylops/waveeqprocessing/marchenko.py, pylops/waveeqprocessing/mdd.py, pytests/test_marchenko.py, pytests/test_waveeqprocessing.py, tutorials/mdd.py
This PR handles https://github.com/PyLops/pylops/issues/392 by cleaning up the MDC, MDD, and Marchenko operators removing all input parameters that have been deprecated through time and enforcing the behavior of `transpose=False`
=> Refractor MDC, MDD and Marchenko

examples/plot_shift.py, pylops/signalprocessing/Shift.py, pytests/test_memoizeoperator.py, pytests/test_oneway.py, pytests/test_shift.py
This PR modified the `Shift` operator to allow user to pass shifts that vary across all axes apart from the one the shift
is applied. An example of how to use this new feature is also provided inn the `plot_shift` example
=> feature: added variable shift to Shift

pylops/LinearOperator.py, pylops/utils/decorators.py, pylops/waveeqprocessing/oneway.py, pytests/test_linearoperator.py, tutorials/linearoperator.py
This PR introduces a new decorator `count` which is used to count the number of matvec/rmatvec/matmat/rmatmat performed by a single operator. These counts are stored in the following variables `matvec_count`,  `rmatvec_count`, `matmat_count`, `rmatmat_count` and can be restarted using the method `reset_count`
=> Added matvec/rmatvec count

MIGRATION_V1_V2.md, examples/plot_causalintegration.py, pylops/avo/poststack.py, pylops/basicoperators/CausalIntegration.py, pylops/basicoperators/DirectionalDerivative.py, pylops/basicoperators/Gradient.py, pylops/basicoperators/Identity.py, pylops/basicoperators/Laplacian.py, pylops/basicoperators/Restriction.py, pylops/basicoperators/SecondDerivative.py, pylops/signalprocessing/Convolve1D.py, pylops/signalprocessing/Convolve2D.py, pylops/signalprocessing/FFT.py, pylops/signalprocessing/FFT2D.py, pylops/signalprocessing/FFTND.py, pylops/waveeqprocessing/marchenko.py, pytests/test_causalintegration.py
The init signature of every operator is reorganized as follows: `Op(..., dtype, name)`.
=> clean: reorganize init signatures for all operators

docs/source/api/index.rst, docs/source/api/others.rst, pylops/optimization/callback.py, pylops/utils/__init__.py, pylops/utils/metrics.py, pytests/test_metrics.py, tutorials/classsolvers.py
Users are usually in the position of creating small routines to compute metrics (mse, snr, psnr, ...) and wrap them into a callback. It makes sense to create a small utility submodule `pylops.utils.metric` where we can add common metrics when 
needed. 
Moreover, leveraging the new Callbacks class, a new callback is created that computes all metrics during iterations
=> feature: metrics

readthedocs.yml
This commit changes the rtd python version to 3.9 in order to work with newly introduced numpy typing annotations.
=> fix: bump rtd python version to 3.9

tutorials/wavefielddecomposition.py
The last cell of the wavefielddecomposition tutorial started to show a problem when using python >3.8 due to changes in scipy lsqr solver tolerances. This problem is solved by applying a scaling to the operator and data.
=> patch: fix problem in wavefielddecomposition tutorial

pylops/optimization/cls_basic.py, pylops/optimization/cls_sparsity.py
A number of problems arose when running these solvers with cupy. They can all be reconducted to 1element arrays staying on the GPU versus scalars being automatically moved back to the CPU. 
This is now enforced throughout for values that we want to store in cost function history lists and similar.
=> fix: enforce float to scalars in optimizers for cupy compatibility

pylops/_torchoperator.py, pylops/torchoperator.py
Currently torch is imported without protection and so it raises an error if torch is not installed. This PR fixes it.
=> fix: modified torchoperator to avoid import errors

pylops/basicoperators/diagonal.py, pytests/test_diagonal.py
The Diagonal operator is currently unable to deal with inputs that are not flattened. This change allows any ND array to be fed as input to the matvec/rmatvec operations.
=> fix: fixed Diagonal to deal with NDarrays

pylops/basicoperators/spread.py, pylops/optimization/cls_sparsity.py, pylops/signalprocessing/chirpradon3d.py, pylops/signalprocessing/dwt.py, pylops/signalprocessing/dwt2d.py, pylops/signalprocessing/fft.py, pylops/signalprocessing/radon2d.py, pylops/signalprocessing/radon3d.py, pylops/utils/deps.py, pylops/utils/describe.py, pylops/waveeqprocessing/twoway.py
See https://github.com/PyLops/pylops/issues/430 for details.
=> Feature : homogenize imports of optional deps

pylops/basicoperators/diagonal.py, pylops/linearoperator.py
Diagonal has its own 'fast' todense method. However, with the introduction of unflattened operations, this method was not correctly handling cases with multidimensional dims. This commit fixes it.
=> Fix: todense in Diagonal method

setup.py
Devito seems to have issues to be installed automatically when running `pip install pylops[advanced]` as part of one of the dependencies. To avoid issues for users, we prefer to take it out and let users install devito manually if interested.
=> minor: remove devito from extras_require

pylops/torchoperator.py, pytests/test_torchoperator.py
This PR enables TorchOperator to work directly with Nd-tensor inputs both in single and batch mode. This is achieved by using the ``Op.dims`` parameter and changing the definitions of `self.matvec` and `self.rmatvec` to be able to handle Nd-arrays
=> Feature: TorchOperator with Nd-array inputs

pylops/torchoperator.py, pytests/test_torchoperator.py
Add a new optional parameter, flatten, to TorchOperator to allow users choosing whether to pass flattened inputs or inputs with shape of Op.dims. This is required at init time as the TorchOperator builds matvec/rmatvec upfront.
=> feature: remove dims and add flatten to TorchOperator

examples/plot_sliding.py, pylops/signalprocessing/radon2d.py, pylops/signalprocessing/radon3d.py
This PR introduces two small improvements to the Radon operators:
- floating point division instead of floor division for when `centeredh==False`. This avoid shifting the axis (alongside normalizing it) when its samples are not multiples of dh
-  creating a normalized axis that is always symmetric when `centeredh==True` also when `nh` is even.
I identified these small inconsistencies when trying to re-implement this example (https://github.com/msacchi/Radon_Py) with PyLops - see https://github.com/PyLops/pylops_notebooks/blob/master/developement/RadonParabolic.ipynb.
=> bug: improved handling of haxes in radons

Makefile
This PR makes it easy for developers to view docs locally by adding `make servedoc` as an option in the `Makefile`.
=> Create servedoc in Makefile

docs/source/api/index.rst, examples/plot_blending.py, pylops/waveeqprocessing/__init__.py, pylops/waveeqprocessing/blending.py, pytests/test_blending.py, tutorials/deblending.py
This PR introduces a new operator, namely `pylops.waveeqprocessing.blending.Blending` which implements the blending of seismic data (or any acoustic data acquired in similar fashion) for simultaneous shooting applications. 
This is based on @NickLuiken work and refractored to be consistent with PyLopsv2 operators' layout. It comprises of 3 private functions/classes implementing the following blending strategies:
- Continouos
- Group
- Half
and a public class which exposes all of them in the same manner (same inputs and shapes of model/data).
Moreover, this PR modifies the Deblending tutorial to use now this operator instead of an operator defined within the example.
=> Feature: Blending

pylops/waveeqprocessing/kirchhoff.py, pylops/waveeqprocessing/lsm.py
This PR adds typing annotations to the `lsm` and `kirchhoff` files. These should be the only two files where typing annotations were missing
=> Typing annotation to lsm and kirchhoff

examples/plot_nonstatconvolve.py, pylops/signalprocessing/_nonstatconvolve2d_cuda.py, pylops/signalprocessing/nonstatconvolve1d.py, pylops/signalprocessing/nonstatconvolve2d.py, tutorials/ilsm.py
This PR fixes some of the issues in #463. Importantly, it limits the number of registers used in the cuda version of `_matvec_rmatvec`. Not doing so causes [this bug](https://stackoverflow.com/questions/68658970/why-launching-a-numba-cuda-kernel-works-with-up-to-640-threads-but-fails-with-6) on my machine.
@mrava87 please check the comments in this PR for further improvements to the code.
=> Improve #463

pylops/signalprocessing/nonstatconvolve2d.py
This commit reverts the _register_multiplications method to its original version to bring the documentation back to life. We can assess later how to remake those methods static.
=> bug: fixed https://github.com/PyLops/pylops/issues/467

docs/source/_static/css/custom.css, docs/source/conf.py
fixes issue: https://github.com/PyLops/pylops/issues/477
demo: 
https://dikwickley-pylops.readthedocs.io/en/latest/tutorials/lsm.html
before:
after:
https://dikwickley-pylops.readthedocs.io/en/latest/tutorials/lsm.html
=> Fixed Figures size in Docs

examples/plot_nonstatfilter.py
We are currently experiencing an error in the build of our documentation which seems to come to the newly introduced example `plot_nonstatfilter` (https://readthedocs.org/api/v2/build/19515033.txt). 
I cannot reproduce this locally!
To get the documentation back up and running this PR changes the backend to numpy for the NonStationaryFilters2D operator in this example.
=> bug: switch NonStationaryFilters2D to numpy in doc

docs/source/adding.rst, docs/source/index.rst, pylops/linearoperator.py, pylops/utils/describe.py, pytests/test_linearoperator.py, tutorials/linearoperator.py
For issue #328 
- Added `_AdjointLinearOperator`, `_TransposeLinearOperator` and `_ProductLinearOperator`
- Added methods `__matmul__`,`__rmatmul__` , `transpose` and `adjoint`
- Made all classes extend the `LinearOperator`
Still need to change/update the docs, if code seems fine...
=> Made LinearOperator independent of spLinearOperator

tutorials/deblending.py
The `deblending` tutorial in the latest documentation seems broken - likely due to an underestimation of the max eigenvalue of the operator.
Here we change the way `maxeig` is computed.
=> doc: fix blowing up in deblending tutorial

pylops/waveeqprocessing/kirchhoff.py, pylops/waveeqprocessing/lsm.py, pytests/test_kirchhoff.py
This PR is mainly aimed at improving the memory efficiency of the `Kirchhoff` operator. 
In the current implementation, we create an overall `trav` table (similar for `amp` in `dynamic=True` mode) of size `nynxnz x nsnr`. Assuming `ns=nr` this scales quadratically with the `ns`. 
In the new implementation, we handle source and receiver tables independently (`trav_srcs` and `trav_recs`) and not merge them into a unique table. Assuming `ns=nr` this scales linearly with the `ns`. 
The following changes are introduced:
- 4 new methods are created: `_travsrcrec_kirch_matvec`, `_travsrcrec_kirch_rmatvec`, `_amp_kirch_matvec`, and `_amp_kirch_rmatvec`, which are the counterparts of `_trav_kirch_matvec`, `_trav_kirch_rmatvec`, `_ampsrcrec_kirch_matvec`, and `_ampsrcrec_kirch_rmatvec` which used …
=> Feature: improve memory handling in Kirchhoff operator

MIGRATION_V1_V2.md, pylops/basicoperators/block.py, pylops/basicoperators/blockdiag.py, pylops/basicoperators/hstack.py, pylops/basicoperators/identity.py, pylops/basicoperators/matrixmult.py, pylops/basicoperators/sum.py, pylops/basicoperators/vstack.py, pylops/basicoperators/zero.py, pylops/linearoperator.py, pylops/optimization/cls_leastsquares.py, pylops/optimization/cls_sparsity.py, pylops/signalprocessing/bilinear.py, pytests/test_basicoperators.py, pytests/test_interpolation.py, tutorials/linearoperator.py
This PR tackles issue https://github.com/PyLops/pylops/issues/500 and aims to provide an easy way for users to drive the behavior of so called ambiguous operators* via keyword arguments, therefore avoid to use global settings or context manager provided by `pylops.config.disabled_ndarray_multiplication`
* An operator is defined ambiguous is the output of either matvec or rmatvec is a 1d array (aka if `dims` or `dimsd` have len=1) . In this case pylops cannot tell whether a user would like a nd array or a 1d array when either rmatvec or matvec is performed on the 1d array from the other method.
A couple of remarks based on the discussion in the issue, before introducing the changes:
-  `Now if that is not possible, I don't like breaking the matrix-like functionality. The operations are …
=> Feature: forceflat property

pylops/utils/metrics.py, pytests/test_metrics.py
This PR handles https://github.com/PyLops/pylops/issues/508 allowing to use the range of `xref` instead of just the maximum (required for non-strictly positive signals - signals with negative values). 
By adding `xmin=0` still ensure backward compatibility, but allows for using effective range by choosing the appropriate xmin
=> patch: allow psnr to use range instead of max

pylops/waveeqprocessing/kirchhoff.py
Recent changes to `kirchhoff` module introduced an error in the `_register_multiplications` function, where `jit` is used instead of `jit_message` to check if Numba is installed. 
As `jit` is imported only when numba is available, passing `engine="numba"` led to an error instead of an automatic fallback to numpy.
=> bug: change jit into jit_message in checks

pylops/linearoperator.py, pylops/utils/decorators.py, pytests/test_solver.py
Basic solvers return 1d- or nd-arrays depending on the attribute dims of the operator indipendently on the shape of x0 and data. This change introduces some logic that reshapes the output to dims only if the starting guess was also an nd-array and the operator does not have forceflat=True.
=> fix: correct basic solvers' handling of ndarrays

Makefile
This PR fixes the `tests` rule as `setup.py` is not available anymore, instead `pytest` is used as the command to start tests.
=> fix: change make rule for tests

.github/workflows/codacy-coverage-reporter.yaml, .pre-commit-config.yaml, pylops/waveeqprocessing/kirchhoff.py, pytests/test_kirchhoff.py
This PR introduces a number of changes to the Kirchhoff operator in an attempt to improve the amplitude fidelity of this modelling process with respect to finite-difference full wavefield modelling. Also follows from https://github.com/PyLops/pylops/issues/439.
Major changes:
- Remove `anglerefl` as the angle `theta` can be computed directly from the incident and reflection angles with normal
- Remove `snell` limitations, this is naturally handled by stationary-phase when summing along all possible image points and src-rec pairs
- Force `amp` to be provided as pair of tables like `trav`
- When `amp` is not provided, compute it as `1/sqrt(dist)` for both source and receiver side in 2D (and `1/dist` in 3D)
- Correct computation of `cos(\theta)`
- Documentation polished and fully consistent …
=> feature: restyling of Kirchhoff operator

pylops/waveeqprocessing/blending.py
BlendingContinuous matvec/rmatvec used * and .H * for some internal calls to operators, which does not allow running this operator with pylops solvers as they disable ndarray_multiplication. Changing this to matvec/rmatvec calls followed by reshape enables the use of this operator with pylops solvers.
=> fix: change BlendingContinuous to work with pylops solvers

pytests/test_ffts.py
This changes `np.float128` and `np.complex256` to `np.longdouble` and `np.clongdouble` in `test_fft.py`. This PR address part of the issues raised in #550, where some M-series Macs do not have `np.float128` and `np.complex256` dtypes.
=> changing to 128/256 bit to c/longdouble

Makefile, docs/source/installation.rst, environment-dev-arm.yml
This PR adds a dev install conda envrionment for arm CPUs. 
Currently `make dev-install_conda` fails on M-series macs as `icc_rt` only works on x86. 
- adds `dev-install_conda_arm` to the make file
- adds `environment-dev-arm.yml` to repo which is the same as `envionment-dev.yml` without `icc_rt` dependency.
- updates `installation.rst` to add `make install dev-install_conda_arm` option to the docs.
=> adding make dev-install_conda_arm

docs/source/adding.rst
Currently the `Implementing new operators` section in our documentation does provide any details about the `@reshaped` decorator. Given its widespread use, I added now some info about it and how to use it.
=> doc: adding info about decorator in new operator doc

README.md, docs/source/credits.rst, pylops/utils/deps.py, pytests/test_ffts.py
This PR changes how optional dependencies import states are checked, to address #548. Importing on Colab now works without requiring adding `os.envion["CUPY_PYLOPS] = "0"`. Instead of using `importlib.util.find_spec` to get state,  this uses `importlib.import_module` in a `try/except` block.
```python
!pip install git+https://github.com/alex-rakowski/pylops.git@optional-depends-checker > /dev/null
import pylops
states_to_check = [
"cupy_enabled",
"cusignal_enabled",
"devito_enabled",
"numba_enabled",
"pyfftw_enabled",
"pywt_enabled",
"skfmm_enabled",
"spgl1_enabled",
"sympy_enabled",
"torch_enabled",
]
for state in states_to_check:
s = getattr(pylops.utils, state)
print(f"{state}: {s}")
cupy_enabled: False
cusignal_enabled: False
devito_enabled: False
numba_enabled: True
pyfftw_enabled: …
```
=> Changing how optional dependencies are import state are checked 

pylops/waveeqprocessing/blending.py
This PR adds some extra logic to nttot in BlendingContinuous which ensures that the minimum length is chosen based on whether the last firing shot requires decimal shift or not.
=> fix: better handling of nttot in BlendingContinuous

pylops/utils/tapers.py, pytests/test_tapers.py
This PR introduces `exponent` to cosinetaper to allow having a taper where adjoint=inverse (when `exponent=0.5`)
=> feat: added exponent to cosinetaper

docs/source/installation.rst, environment-dev-arm.yml, environment-dev.yml, examples/plot_dtcwt.py, pylops/signalprocessing/__init__.py, pylops/signalprocessing/dct.py, pylops/signalprocessing/dtcwt.py, pylops/utils/deps.py, pyproject.toml, pytests/test_dtcwt.py, requirements-dev.txt
This PR introduced the `DTCWT` operator in the signal processing submodule that implements the Dual-Tree Complex Wavelet Transform
=> feat: added DTCWT 1d operator

pylops/signalprocessing/dtcwt.py
The previous PR introduced an unwanted import error of pylops when `dtcwt` was not installed; this was due to the fact we used dtcwt for typing annotation. 
The current solution is not to use for any typing annotation to ensure that no problem arises if `dtcwt` is not installed, given that it is an optional dependency
=> fix: ensure dtcwt is not used in typing annotations

pylops/utils/signalprocessing.py, pytests/test_signalutils.py
closes #572. 
Quick fix but I have also added a unit test to see if the regularisation is applied when NOT using dips as a way to check which algorithm is used.
=> Fix incorrect dips check in `slope_estimation

pylops/signalprocessing/dtcwt.py
This PR adds typing annotations for `dtcwt` objects in a safe way, such that it doesn't result in an error if the library is not installed
=> doc: added safe typing to dtcwt

docs/source/gpu.rst, pylops/signalprocessing/patch2d.py, pylops/signalprocessing/patch3d.py, pylops/signalprocessing/sliding1d.py, pylops/signalprocessing/sliding2d.py, pylops/signalprocessing/sliding3d.py, pylops/utils/backend.py, pytests/test_patching.py, pytests/test_sliding.py
In this PR, I provide a new implementation for all Sliding and Patch operators that presents the following features:
- the operators are now directly implemented with `_matvec` and `_rmatvec` methods. The old implementation, although elegant in that it relied on using other pylops operators, showed to be inefficient especially in cases with very large number of windows.
- Two kind of operators `Op` can be provided: the first applies a single transformation to each window separately (as default from before); the second applies the transformation to all of the windows at the same time.
- `nproc` in Sliding3D is deprecated since we do not use anymore HStack/VStack operators that have a multi-threading option. Currently, all of the new implementations are single threaded (although inside they …
=> Feature: new Sliding and Patch operators

pylops/utils/backend.py
Fixes https://github.com/PyLops/pylops/issues/579
=> bug: to_cupy_conditional

README.md, docs/source/api/index.rst, docs/source/credits.rst, examples/plot_wavelet.py, pylops/signalprocessing/__init__.py, pylops/signalprocessing/dwtnd.py, pytests/test_dwts.py
This PR adds support for N-dimensional discrete wavelet transforms via a new linear operator `DWTND`.
This is a super minor addition building upon what is already implemented with the `DWT` and `DWT2D` operators. This simply  generalizes those operators to N dimensions, something that we saw need for in a recent application of ours.
=> Feature: N-dimensional discrete wavelet transforms

Makefile, environment-dev-arm.yml, environment-dev.yml, requirements-dev.txt
This PR fixes all requirements/environment files to ensure that the CPU version torch is installed even if a GPU is detected
=> build: force torch cpuonly

.github/workflows/build.yaml, azure-pipelines.yml, docs/source/installation.rst, environment-dev-arm.yml, environment-dev.yml, environment.yml, pylops/optimization/cls_leastsquares.py, pyproject.toml, pytests/test_leastsquares.py, pytests/test_linearoperator.py, pytests/test_solver.py, requirements-dev.txt
This PR is aimed at solving some of the issues arising in our test suite when scipy v1.14 is used. This is mostly related to an (announced) breaking change in the new version for the `scipy.sparse.linalg.cg` solver, namely:
```
The tol argument of scipy.sparse.linalg.{bcg,bicstab,cg,cgs,gcrotmk, mres,lgmres,minres,qmr,tfqmr} 
has been removed in favour of rtol. Furthermore, the default value of atol for these 
functions has changed to 0.0.
```
See https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html
As a result of this change, we decided to:
- Bump the minimal python requirement to 3.9
- Bump the minimal scipy requirement to 1.13
- Change `tol` into `atol` when passed to the scipy cg solver in `NormalEquationsInversion`
=> Patch: scipy v1.11

pylops/waveeqprocessing/twoway.py
Hey, my name is Gustavo Coelho. I hope this PR is useful for you.
During the creation of the Born operator, Devito uses an optimization technique that caches the result so that for subsequent executions with the same parameters, it doesn't need to recreate the operator, but simply retrieves it from the cache.
However, with a new solver being created for each shot, Pylops couldn't take advantage of this feature. This PR aims to address this issue by moving the creation of the solver outside the shots iteration loop.
Additionally, we are working on other features for Pylops and plan to make further contributions soon.
=> Update that increases performance (AcousticWave2D)

.readthedocs.yaml, docs/source/installation.rst, environment-dev-arm.yml, environment-dev.yml, environment.yml, pylops/basicoperators/restriction.py, pylops/linearoperator.py, pyproject.toml, pytests/test_dtcwt.py, pytests/test_sparsity.py, pytests/test_torchoperator.py, requirements-dev.txt, requirements-doc.txt
This PR aims to allow users to use pylops with numpy>=2.0.0.
Currently we need to make the following work-arounds:
- disable tests for `spgl1` until new release of `spgl1` library
- disable tests for `DTCWT` until new release of `dtcwt` library
- disable tests for `TorchOperator` in darwin os (currently torch does give this error `RuntimeError: Numpy is not available`)
=> Feature: migrate to numpy v2.0.0

pylops/waveeqprocessing/_twoway.py, pylops/waveeqprocessing/twoway.py
This PR moves `_CustomSource` to a private file to avoid pylops raising a import error when devito is not installed. Similarly, an `AcousticWaveSolverType` is created for type hinting
=> bug: move _CustomSource to private file

CHANGELOG.md, docs/source/changelog.rst, docs/source/installation.rst, pylops/utils/tapers.py, pylops/waveeqprocessing/oneway.py, pytests/test_sparsity.py
This PR is created in preparation of the deployment of v2.3.0. 
Alongside changing the changelog files, it restores tests for spgl1 as it is now compatible with numpy2
=> Prepare for v2.3.0

pylops/utils/backend.py
Fixes https://github.com/PyLops/pylops/issues/606
=> bug: protect use of jnp if jax is not installed

pylops/basicoperators/firstderivative.py, pylops/basicoperators/laplacian.py, pylops/basicoperators/restriction.py, pylops/basicoperators/secondderivative.py, pylops/basicoperators/transpose.py, pylops/signalprocessing/_baseffts.py, pylops/signalprocessing/convolvend.py, pylops/signalprocessing/shift.py, pylops/utils/backend.py
This PR introduces a new method in the `backend` submodule aimed at importing `normalize_axis_index` from the correct numpy submodule based on the numpy version used.
=> Handle numpy warning for normalize_axis_index

tutorials/ilsm.py
This PR fixes a problem in the `ilsm` tutorial that was introduced in v2.2.0 due to improvement to the `pylops.waveeqprocessing.Kirchhoff` operator, which however changed the dynamic range of its outputs.
=> doc: fix vlims of ilsm tutorial

.github/workflows/build.yaml, .github/workflows/codacy-coverage-reporter.yaml, .readthedocs.yaml, Makefile, azure-pipelines.yml, requirements-dev.txt, requirements-torch.txt
Closes https://github.com/PyLops/pylops/issues/597 by adding a `requirements-torch.txt` file that installs PyTorch from a specific index. 
We have also simplified the GA installation process removing unneeded `if [ -f requirements.txt ]; then pip install -r requirements-dev.txt; fi`, simply installing all dependencies as follows:
```
pip install -r requirements-dev.txt
pip install -r requirements-torch.txt
```
=> build: added separate requirement file for torch

pylops/basicoperators/_spread_numba.py
This PR fixes a problem introduced in Spread with latest versions of numba. This is due to the way we used to handle nans, a much cleaner way is used now with math.isnan without having to first convert to integrers.
=> bug: fix nans in Spread

CHANGELOG.md, docs/source/api/index.rst, docs/source/api/others.rst, docs/source/gpu.rst, examples/plot_fourierradon.py, examples/plot_seismicevents.py, pylops/signalprocessing/__init__.py, pylops/signalprocessing/_fourierradon2d_cuda.py, pylops/signalprocessing/_fourierradon2d_numba.py, pylops/signalprocessing/_fourierradon3d_cuda.py, pylops/signalprocessing/_fourierradon3d_numba.py, pylops/signalprocessing/_nonstatconvolve2d_cuda.py, pylops/signalprocessing/fourierradon2d.py, pylops/signalprocessing/fourierradon3d.py, pylops/signalprocessing/radon2d.py, pylops/signalprocessing/radon3d.py, pylops/utils/estimators.py, pylops/utils/seismicevents.py, pytests/test_fourierradon.py
This PR introduces 2 new operators, namely `FourierRadon2D` and `FourierRadon3D` that perform linear/parabolic Radon transform in the frequency domain.
Both of them have 3 backends:
- `numpy`: can run with both numpy and cupy arrays, suboptimal performance
- `numba`: optimal performance for numpy arrays
- `cuda`: optimal performance for cupy arrays (uses a numba-cuda custom kernel for part of the operations in matvec/rmatvec
To test the parabolic transform in 3D, a new utility function `pylops.utils.seismicevents.parabolic3d` is also added.
The new operators are showcased in `plot_fourierradon.py`. Moreover, two notebook have been added at https://github.com/PyLops/pylops_notebooks/blob/master/developement/Radon-Fourier.ipynb and …
=> FourierRadon2D and FourierRadon3D

pylops/optimization/cls_leastsquares.py
PyLops solvers output the solution as a nd-shaped array if the initial model is fed as nd-arrays or if the initial model is not fed (x0=0) and the operator has forceflat=False. As a side effect, if x0 is NOT passed as a kwarg (but just as the third arg of the solver) and the operator forceflat=False, the output is reshaped even if x0 is a flattened array. I fix this inconsistency making x0 a kwarg when basic solvers are called within a leastsquares solver.
=> bug: ensure array shape consistency in leastsquares solvers

docs/source/conf.py
I personally dislike it a lot when I come to the documentation of a source code, but there is no easy/quick link to the code repo, which means I have to google to find the repo ;-)
Adding the `"github_url"` to the `"html_theme_options"` should add a GitHub-link-button on the top-right corner, next to the switch for light/dark theme.
I haven't built the PyLops-docs to check it, but this is how it looks on the empymod website:
=> Add button to GitHub Repo

pylops/signalprocessing/_fourierradon2d_cuda.py, pylops/signalprocessing/_fourierradon3d_cuda.py, pylops/signalprocessing/fourierradon2d.py, pylops/signalprocessing/fourierradon3d.py
This PR introduces a number of changes to the radonfourier cuda implementations based on discussions in https://github.com/PyLops/pylops/pull/611
Those changes improve the speed of both the 2D and 3D implementations (see https://github.com/PyLops/pylops_notebooks/blob/master/developement-cupy/Radon-Fourier.ipynb):
2D: forward 10.2ms, adjoint 11.2ms  --> forward 2.5ms, adjoint 2.4ms
3D: forward 9.8ms, adjoint 6.1ms  --> forward 3.1ms, adjoint 1.65ms
I would like to get this changes in before moving on to adding the grid-strided loops (https://github.com/PyLops/pylops/issues/616)
=> feat: speedup fourierradon with engine=cuda

pylops/waveeqprocessing/seismicinterpolation.py
For trace interpolation, it is necessary to define either `sampling` or both `taxis` and `spataxis`. In case of using the latter, the function `SeismicInterpolation` is supposed to calculate the sampling. However, the calculated `sampling` was always `[0, 0]`. 
This PR fixes this problem.
=> Bug: fix sampling when not given

docs/source/installation.rst
This change is made in the light of the fact that `np.dot` does not seem to multi-thread anyone (as I am quite sure used to do in the past given the fact we built this small test example around it...)
=> minor: switch np.dot to np.matmul in code snipped in installation

pylops/optimization/basic.py, pylops/optimization/cls_basic.py
The documentation of [pylops.lsqr](https://pylops.readthedocs.io/en/stable/api/generated/pylops.optimization.basic.lsqr.html) was missing the returns of `iiter` and `xnorm`. 
They were added to the docs of all related functions and methods.
For `iiter` the same phrasing as for [`scipy.sparse.linalg.lsqr`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lsqr.html) was used.
For `xnorm`, the mathematical style of `pylops` was adopted.
Closes #637
=> Added missing `iiter` and `xnorm` to the documentation of `pylops.lsqr`

pylops/optimization/cls_sparsity.py, pylops/optimization/sparsity.py
This commit changes the signature of the callback of the omp solver, which provided only the non-zero coefficients (in x) without their indices - added now in the second input parameter (col).
=> bug: missing cols in callback of omp solver

pylops/signalprocessing/fft.py, pylops/signalprocessing/fft2d.py, pylops/signalprocessing/fftnd.py, pytests/test_ffts.py
This PR introduces the possibility to pass keywords arguments to the `FFT`, `FFT2D`, and `FFTND` operators, which allows one to pass any additional parameter to the numpy/scipy/fftw/cupy/jax methods used in the operators.
=> feat: added kwargs_fft to all fft operators

pylops/utils/backend.py
Added safeguards to ensure cp and jnp are reached only if installed.
=> bug: added safeguards to get_module_name

.github/workflows/build.yaml, .github/workflows/codacy-coverage-reporter.yaml, azure-pipelines.yml, requirements-dev.txt
This PR temporarily removes `python3.11` from the various CI actions due to know building issues of `scikit-fmm` - soon to be fixed
=> CI: Fix Github Action

pytests/test_pytensoroperator.py
This PR adds `pytensor.config.gcc__cxxflags = "-Wno-c++11-narrowing"` as already explained in the installation part of the documentation to ensure tests can be run on macOS (without this I was getting a CompileError locally)
=> test: make pytensoroperator tests run on macOS

CHANGELOG.md, docs/source/changelog.rst, docs/source/sg_execution_times.rst
=> release: prepare for v2.5.0
