- CHANGELOG.md
- docs/source/api/index.rst
- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/index.rst
- examples/plot_causalintegration.py
- pylops/__init__.py
- pylops/basicoperators/CausalIntegration.py
- pylops/basicoperators/FirstDerivative.py
- pylops/basicoperators/SecondDerivative.py
- pylops/basicoperators/__init__.py
- pylops/optimization/leastsquares.py
- pytests/test_basicoperators.py
- pytests/test_causalintegration.py
> Added CausalIntegration operator

- docs/source/roadmap.rst
Nice roadmap. Just by flicking through I thought more descriptive issue-links might be helpful/informative.
> More descriptive issue-links

- CHANGELOG.md
- Makefile
- docs/source/changelog.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/performance.rst
- docs/source/roadmap.rst
- Added documentation for setting up pylops with conda mkl and ensure best performance.
- Added changelog for version 1.2.0
> Documentation for optimised code and changelog v1.2.0

- .coveragerc
- .gitignore
- .travis.yml
- docs/source/api/index.rst
- examples/plot_restriction.py
- pylops/LinearOperator.py
- pylops/basicoperators/Diagonal.py
- pylops/basicoperators/Restriction.py
Small changes in the documentation of the API (defined now as 3 level API)
Added coverage files a…nd modified travis file to run coverage test.
> Change in the doc of the API. Added coverage.

- pylops/basicoperators/Laplacian.py
- pylops/basicoperators/SecondDerivative.py
- pytests/test_derivative.py
There was a scaling issue in SecondDerivative; the finite difference was scale with h in stead of h^2. I fixed the scaling and the unit tests.
> Fix scaling and tests of SecondDerivative

- README.md
- azure-pipelines.yml
- docs/source/api/index.rst
- docs/source/installation.rst
- examples/plot_sliding.py
- pylops/LinearOperator.py
- pylops/avo/poststack.py
- pylops/basicoperators/Spread.py
- pylops/optimization/sparsity.py
- pylops/signalprocessing/FFTND.py
- pylops/signalprocessing/Radon2D.py
- pylops/signalprocessing/Radon3D.py
- pylops/signalprocessing/Sliding2D.py
- pylops/signalprocessing/Sliding3D.py
- pylops/signalprocessing/__init__.py
- pylops/utils/tapers.py
- pylops/waveeqprocessing/__init__.py
- pylops/waveeqprocessing/seismicinterpolation.py
- pytests/test_seismicinterpolation.py
- pytests/test_sliding.py
- tutorials/seismicinterpolation.py
- added Sliding3D operator
- added seismicinterpolation application
- better handling of edge tapers in Sliding2D
- added possibility to choose number of iterations in eigenvalue computation for ISTA and FISTA
- added show option to ISTA and FISTA
- azure-pipeline file
> [Core+Geo] Added Sliding3D operator and seismicinterpolation application

- docs/source/api/index.rst
- pylops/signalprocessing/Radon2D.py
- pylops/signalprocessing/Radon3D.py
- pylops/waveeqprocessing/__init__.py
- pylops/waveeqprocessing/seismicinterpolation.py
- pylops/waveeqprocessing/wavedecomposition.py
- pytests/test_tapers.py
- pytests/test_wavedecomposition.py
- setup.py
- tutorials/wavefielddecomposition.py
Added operators and app for seismic wavefield decomposition
> [Geo] Seismic wavefield decomposition

- docs/source/_static/style.css
- docs/source/api/index.rst
- docs/source/performance.rst
- docs/source/roadmap.rst
- environment-dev.yml
- pylops/avo/poststack.py
- pylops/avo/prestack.py
- pylops/basicoperators/Spread.py
- pylops/optimization/sparsity.py
- pylops/signalprocessing/FFT.py
- pylops/waveeqprocessing/__init__.py
- pylops/waveeqprocessing/lsm.py
- pylops/waveeqprocessing/marchenko.py
- pylops/waveeqprocessing/wavedecomposition.py
- pytests/test_ffts.py
- pytests/test_lsm.py
- pytests/test_prestack.py
- requirements-dev.txt
- setup.py
- tutorials/lsm.py
- tutorials/mdd.py
- tutorials/poststack.py
- tutorials/prestack.py
Mostly focused on Demigration and LSM with small modification to Spread to accomodate for this new application and small changes in tutorials to reduce run time.
> [Geo] Demigration and LSM

- docs/source/api/index.rst
- examples/plot_roll.py
- pylops/LinearOperator.py
- pylops/__init__.py
- pylops/basicoperators/Roll.py
- pylops/basicoperators/__init__.py
- pylops/signalprocessing/Fredholm1.py
- pylops/waveeqprocessing/marchenko.py
- pylops/waveeqprocessing/mdd.py
- pytests/test_basicoperators.py
- pytests/test_fredholm.py
- pytests/test_linearoperator.py
- pytests/test_waveeqprocessing.py
- tutorials/linearoperator.py
- tutorials/marchenko.py
- Work with new MDC
- Allow storing on R (previously R(t) and R(-t) were both required)
- conj method in LinearOperator and Roll operator are created as by-product to achieve the above.
> Optimized Marchenko

- docs/source/api/index.rst
- examples/plot_convolve.py
- examples/plot_matrixmult.py
- examples/plot_wavest.py
- pylops/avo/poststack.py
- pylops/basicoperators/BlockDiag.py
- pylops/basicoperators/Diagonal.py
- pylops/basicoperators/HStack.py
- pylops/basicoperators/Transpose.py
- pylops/basicoperators/VStack.py
- pylops/optimization/leastsquares.py
- pylops/signalprocessing/Convolve1D.py
- pylops/signalprocessing/Convolve2D.py
- pylops/signalprocessing/ConvolveND.py
- pylops/signalprocessing/Fredholm1.py
- pylops/signalprocessing/__init__.py
- pylops/utils/dottest.py
- pylops/waveeqprocessing/mdd.py
- pytests/test_convolve.py
- pytests/test_fredholm.py
- tutorials/marchenko.py
- tutorials/mdd.py
Added ConvolveND and optimised Convolve1D and Convolve2D.
> [Core] ConvolveND

- README.md
- docs/source/credits.rst
- examples/plot_restriction.py
- pylops/signalprocessing/Interp.py
- pytests/test_interpolation.py
- Added sinc interpolation to Interp operator
> [Core] sinc interpolation

- examples/plot_derivative.py
- pylops/basicoperators/DirectionalDerivative.py
- pylops/basicoperators/FirstDerivative.py
- pylops/basicoperators/Gradient.py
- pylops/signalprocessing/Seislet.py
- pytests/test_derivative.py
- pytests/test_seislet.py
This PR contains two new backends (forward and backward) for the FirstDerivative and a new backend (linear) for the Seislet operators.
> Forward/backward to FirstDerivative and linear to Seislet

- pylops/optimization/sparsity.py
Use complex-friendly implementation for _softthreshold and substitute _shrinkage for _softthreshold
See #170
> Use complex-friendly _softthreshold

- pylops/basicoperators/Smoothing2D.py
- pylops/signalprocessing/Convolve2D.py
- pylops/signalprocessing/ConvolveND.py
- pytests/test_smoothing.py
Corrected handling of filters with less dimensions than the input dataset.
> Fix bug in Convolve2D and ConvolveND

- examples/plot_cgls.py
- pylops/__init__.py
- pylops/optimization/solver.py
- pylops/utils/__init__.py
- pylops/utils/backend.py
- pylops/utils/deps.py
- pylops/utils/dottest.py
- pytests/test_solver.py
- Added deps and backend utils
- Modified dottest to work with cupy
- Added cg and cgls solvers
> Added utils and solvers for cupy

- pylops/optimization/sparsity.py
This includes the following changes:
- Switch from np to ncp in all solvers
- Use of cgls in various solvers instead of lsqr with cupy arrays
- Switch to power_iteration for cupy arrays in ISTA and FISTA
- Explicit handling of print of complex numbers in ISTA and FISTA logs
- Ensure creation of zeros arrays with correct backend and type.
> Modified sparsity module to work with cups arrays

- docs/source/api/index.rst
- docs/source/gpu.rst
- docs/source/papers.rst
- pylops/LinearOperator.py
- pylops/__init__.py
- pylops/basicoperators/MatrixMult.py
- pylops/basicoperators/MemoizeOperator.py
- pylops/basicoperators/__init__.py
- pylops/utils/dottest.py
- pytests/test_linearoperator.py
- pytests/test_memoizeoperator.py
- tutorials/realcomplex.py
- Added MemoizeOperator
- Created toreal and toimag methods in LinearOperator to solve complex number inverse problems as stack of real and imaginary parts
> MemoizeOperator

- pylops/utils/dottest.py
- pytests/test_interpolation.py
Resolve https://github.com/PyLops/pylops/issues/229.
> Fix bug in dottest for imag

- pylops/signalprocessing/Radon2D.py
- pylops/signalprocessing/Radon3D.py
Modified handling of haxis in Radon2D and Radon3D
such as it allows for shifted parametric curves (eg
hyperbola fixed axis at any horizontal location).
> Changed Radon haxis

- pylops/signalprocessing/FFT.py
- pylops/signalprocessing/Radon2D.py
- pylops/signalprocessing/Radon3D.py
Modified handling of 1d signals in _FFT_fftw which led to an error
when passing a single number (of int type) for the dims parameter.
> Fix bug in FFT with fftw backend for 1d signals

- docs/source/api/others.rst
- docs/source/performance.rst
- environment-dev.yml
- examples/plot_describe.py
- pylops/utils/describe.py
- pytests/test_describe.py
- requirements-dev.txt
The describe method provides a mathematical description
of a PyLops operator. Addresses https://github.com/PyLops/pylops/issues/293.
> Feature: Added describe method

- examples/plot_slopeest.py
This PR updates the example `plot_slopeest.py` based on the bugfix incorporated by #298
> bugfix: Update example after bugfix to slope_estimate

- pylops/signalprocessing/Sliding1D.py
- pylops/signalprocessing/Sliding2D.py
- pylops/signalprocessing/Sliding3D.py
> bugfix: Restriction must inherit Op.dtype

- examples/plot_nmo.py
Closes #29.
This PR introduces an example of the implementation of a classic NMO operator. It offers an implementation from scratch, but also one using the `Spread` operator.
> feature: NMO example

- pylops/utils/dottest.py
#335 and #336; but backwards compatible - just as discussed in #336
> #335 and #336; but backwards compatible

- docs/source/conf.py
- examples/plot_bilinear.py
- examples/plot_conj.py
- examples/plot_imag.py
- examples/plot_pad.py
- examples/plot_real.py
- examples/plot_slopeest.py
- pytests/test_avo.py
- pytests/test_chirpradon.py
- pytests/test_combine.py
- pytests/test_describe.py
- pytests/test_linearoperator.py
- pytests/test_lsm.py
- pytests/test_memoizeoperator.py
- pytests/test_oneway.py
- pytests/test_seismicinterpolation.py
- pytests/test_signalutils.py
- pytests/test_smoothing.py
- pytests/test_transpose.py
> fix: flake8 warnings and errors for examples, tutorials, docs, pytests

- pylops/signalprocessing/Convolve1D.py
See https://github.com/PyLops/pylops/issues/358 for details.
> fix: handle case with dims scalar in Convolve1D

- pylops/signalprocessing/Patch2D.py
- pytests/test_patching.py
Added option to use patch-wise scalings.
> feature: added scalings to Patch2d

- .github/workflows/flake8.yaml
- Makefile
- docs/source/contributing.rst
- environment-dev.yml
- requirements-dev.txt
- setup.cfg
Handles https://github.com/PyLops/pylops/issues/352
> CI: added flake8 github action

- .pre-commit-config.yaml
See https://github.com/PyLops/pylops/issues/368.
> bug: fix black version in pre-commit

- .pre-commit-config.yaml
- pylops/waveeqprocessing/oneway.py
- pytests/test_oneway.py
Fixes https://github.com/PyLops/pylops/issues/377
> fix: Deghosing tutorial broken after v1.17.0

- README.md
Handles https://github.com/PyLops/pylops/issues/379.
> minor: revamped README

- README.md
and also list from newest to oldest
> add Transform 2022 to tutorials

- README.md
> Update README.md to link to stable and not latest

- docs/source/api/index.rst
- docs/source/api/others.rst
- examples/plot_patching.py
- pylops/signalprocessing/Patch3D.py
- pylops/signalprocessing/__init__.py
- pylops/utils/tapers.py
- pytests/test_patching.py
This PR extends the `pylops.signalprocessing.Patch2D` operator to three-dimensional dataset.
- Correctly handle edges
- Add example
- Add test
> feature: Add Patch3D operator

- docs/source/api/others.rst
- examples/plot_wavs.py
- pylops/utils/wavelets.py
- pytests/test_wavelets.py
Added new wavelets in pylops.utils.wavelets module and cleaned up the module to reduce code repetition.
> feature: added klauder and ormsby wavelets

- pylops/basicoperators/FirstDerivative.py
- pylops/basicoperators/SecondDerivative.py
- pytests/test_derivative.py
This commit contains a number of additions to FirstDerivative and SecondDerivative that include fifth-order 1st derivative and backward 2nd derivative as well as improvements in their docstrings.
> feature: added fifth-order 1st derivative and backward 2nd derivative

- pylops/LinearOperator.py
- pylops/basicoperators/Restriction.py
- pylops/optimization/cls_basic.py
This PR starts to handle bugs arising when running the pylops v2 codebase on cupy. This is expected to grow with time whilst checking all notebooks in https://github.com/PyLops/pylops_notebooks/tree/master/developement-cupy.
> bug: small fixes to work with cupy

- pylops/signalprocessing/_BaseFFTs.py
Handles https://github.com/PyLops/pylops/issues/407.
> fix: forced nffts in FFT*D to be tuple for cupy

- pylops/waveeqprocessing/twoway.py
This commit handles https://github.com/PyLops/pylops/issues/421.
> bug: protect devito import

- pylops/signalprocessing/Bilinear.py
- pylops/signalprocessing/ChirpRadon2D.py
- pylops/signalprocessing/ChirpRadon3D.py
- pylops/signalprocessing/Convolve1D.py
- pylops/signalprocessing/Convolve2D.py
- pylops/signalprocessing/ConvolveND.py
- pylops/signalprocessing/DWT.py
- pylops/signalprocessing/DWT2D.py
- pylops/signalprocessing/FFT.py
- pylops/signalprocessing/FFT2D.py
- pylops/signalprocessing/FFTND.py
- pylops/signalprocessing/Fredholm1.py
- pylops/signalprocessing/Interp.py
- pylops/signalprocessing/Patch2D.py
- pylops/signalprocessing/Patch3D.py
- pylops/signalprocessing/Radon2D.py
- pylops/signalprocessing/Radon3D.py
- pylops/signalprocessing/Seislet.py
- pylops/signalprocessing/Shift.py
- pylops/signalprocessing/Sliding1D.py
- pylops/signalprocessing/Sliding2D.py
- pylops/signalprocessing/Sliding3D.py
This PR handles https://github.com/PyLops/pylops/issues/278 and provides typing annotation to all functions and classes of pylops module signalprocessing.
> feature: typing annotation (signalprocessing)

- MIGRATION_V1_V2.md
- pylops/linearoperator.py
- pylops/optimization/cls_basic.py
- pylops/optimization/cls_leastsquares.py
- pylops/optimization/cls_sparsity.py
- pylops/signalprocessing/fftnd.py
- pylops/signalprocessing/interp.py
- pylops/utils/backend.py
- pytests/test_leastsquares.py
This commit fixes a number of bugs that were discovered when re-running all development-cupy notebooks with the pylopsv2 codebase.
> fix: miscellanous of bug fixes for cupy

- pylops/linearoperator.py
This commit handles https://github.com/PyLops/pylops/issues/451.
> bug: force explicit=False on any composite operator

- examples/plot_l1l1.py
- examples/plot_linearregr.py
- pylops/optimization/cls_sparsity.py
- pylops/optimization/sparsity.py
- pytests/test_sparsity.py
This PR adds a new formulation of IRLS following https://github.com/PyLops/pylops/issues/324
> feature: added irls datamodel

- README.md
- docs/source/credits.rst
This PR adds two new contributors to the README and documentation.
> doc: added new contributors

- pylops/utils/tapers.py
Handles https://github.com/PyLops/pylops/issues/456.
> bug: fix nan in taper

- docs/source/adding.rst
- docs/source/addingsolver.rst
- docs/source/changelog.rst
- docs/source/conf.py
- pylops/avo/poststack.py
- pylops/basicoperators/block.py
- pylops/basicoperators/diagonal.py
- pylops/linearoperator.py
- pylops/optimization/basic.py
- pylops/optimization/cls_basic.py
- pylops/optimization/cls_sparsity.py
- pylops/optimization/sparsity.py
- pylops/signalprocessing/convolve1d.py
- pylops/signalprocessing/convolvend.py
- pylops/utils/describe.py
- pylops/utils/multiproc.py
- pylops/utils/signalprocessing.py
- pylops/waveeqprocessing/marchenko.py
- pylops/waveeqprocessing/mdd.py
Checking the latest [codeacy reports](https://app.codacy.com/gh/PyLops/pylops/issues), several issues were highlighted. This PR attempts to fix most of them, including some issues with the docs. In particular, the last commit ostensibly fixes the issue of `WARNING: multiple files...` when detecting `ipynb` and `md5` files.
> Patch code quality

- pylops/basicoperators/blockdiag.py
- pylops/basicoperators/hstack.py
- pylops/basicoperators/vstack.py
- pylops/linearoperator.py
Tested on scipy 1.17.3, 1.18.0 and 1.10.0.
> Closes #469

- docs/source/conf.py
- readthedocs.yml
- requirements-doc.txt
issue: https://github.com/PyLops/pylops/issues/443
@mrava87 made a fresh new PR (closed old one #473) . please review it
> migrated doc build py version and updated sphinx theme

- pytests/test_basicoperators.py
- pytests/test_convolve.py
- pytests/test_diagonal.py
- pytests/test_dwts.py
- pytests/test_ffts.py
- pytests/test_fredholm.py
- pytests/test_functionoperator.py
- pytests/test_kronecker.py
- pytests/test_nonstatconvolve.py
- pytests/test_shift.py
- pytests/test_smoothing.py
these additions are regarding issue #327
> added Atol and Btol in scipy lsqr for all tests

- tutorials/solvers.py
Fixes https://github.com/PyLops/pylops/issues/503
> doc: fixes https://github.com/PyLops/pylops/issues/503

- examples/plot_convolve.py
- examples/plot_ista.py
- pylops/signalprocessing/convolve1d.py
- pytests/test_convolve.py
- pytests/test_kirchhoff.py
- pytests/test_lsm.py
This PR generalizes the `Convolve1D` operator to handle both the scenario of short filter (and longer input) as well as short input (and longer filter). The latter is introduced here.
> Feature: Convolve1D with short and long filters

- pylops/waveeqprocessing/kirchhoff.py
Same as https://github.com/PyLops/pylops/pull/511
> bug: fixed skfmm check in kirchhoff

- README.md
- docs/source/api/index.rst
- docs/source/credits.rst
- pylops/signalprocessing/__init__.py
- pylops/signalprocessing/_nonstatconvolve3d_cuda.py
- pylops/signalprocessing/nonstatconvolve2d.py
- pylops/signalprocessing/nonstatconvolve3d.py
- pytests/test_nonstatconvolve.py
This PR adds a new operator performing 3D non-stationary convolution
> feature: added nonstatconvolve3d operator

- pylops/basicoperators/restriction.py
This commit is related to https://github.com/PyLops/pylops/issues/500. However, when this problem was solved for most operators, `Restriction` was not taken into account.
> bug: add forceflat to restriction to avoid unexpected unflattening of adjoint

- pylops/avo/poststack.py
- pylops/avo/prestack.py
- pylops/utils/signalprocessing.py
- pytests/test_signalutils.py
Fixed convmtx as discussed in https://github.com/PyLops/pylops/issues/517
> bug: fixed convmtx

- pylops/waveeqprocessing/blending.py
A second implementation is provided for the matvec/rmatvec routines of BlendingContinuous, where shifting is performed simultaneously for all sources. This implementation is more favourable when dealing with small number of receivers.
> minor: second implementation to BlendingContinuous

- docs/source/faq.rst
- docs/source/gpu.rst
- docs/source/installation.rst
- pylops/signalprocessing/convolve1d.py
- pylops/utils/backend.py
- pylops/utils/deps.py
This PR switches all operators using cusignal to cupy as cusignal is now deprecated (see official documentation)
> feature: remove cusignal dependency

- docs/source/api/index.rst
Add `DTCWT` to api documentation
> doc: add dtcwt to doc api

- .github/workflows/build.yaml
- .github/workflows/codacy-coverage-reporter.yaml
- .github/workflows/flake8.yaml
Upgrade versions of checkout and setup-python
> build: modernized ci

- pylops/signalprocessing/fredholm1.py
- pylops/waveeqprocessing/mdd.py
This PR:
- removes ravel from Fredholm1 _matvev
- adds args_FFT1 to MDC
> minor: Fredholm1 and MDC small changes

- examples/plot_twoway.py
- pylops/waveeqprocessing/twoway.py
This PR introduces a new method called `updatesrc` to AcousticWave2D which allows one to pass a user-defined source wavelet.
An example is also added to the gallery to show how to use AcousticWave2D - currently we did not add any example
> feature: added updatesrc method to AcousticWave2D

- pylops/waveeqprocessing/twoway.py
Hi!
This pull request is related to #603
> Removes the creation of the solver from within the shots iteration loop.
